version: 1.0.{build}

image:
- Visual Studio 2022

install:
- dir C:\
- set PATH=C:\Ruby26-x64\bin;%PATH%
- ruby -v
- pwsh --Version
- pwsh .\scripts\Generate-Message-Sources.ps1

before_test:
- ruby -v

build_script:
- ps: dotnet build -c Release --framework net6.0

test_script:
- dotnet test -c Release --no-build --no-restore UnitTests -l trx
- dotnet test UnitTests
- dotnet test AcceptanceTest
